"""Add admin and contact message models

Revision ID: 1750d7a0b4a5
Revises: 
Create Date: 2025-10-25 16:57:38.154862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1750d7a0b4a5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminder_setting', schema=None) as batch_op:
        batch_op.alter_column('reminder_time_utc',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.String(length=10),
               existing_nullable=True)
        batch_op.drop_column('timezone_offset')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminder_setting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timezone_offset', sa.INTEGER(), server_default=sa.text('0'), nullable=False))
        batch_op.alter_column('reminder_time_utc',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=5),
               existing_nullable=True)

    # ### end Alembic commands ###
